get:
  tags:
    - 36協定設定
  summary: /v1/article-36-agreement-settings
  description: "36協定設定を取得する。"
  operationId: get-article-36-agreement-settings
  security:
    - ApplicationJWT: []
  parameters:
    - $ref: ../../components/parameters/common.yaml#/components/parameters/page
    - $ref: ../../components/parameters/common.yaml#/components/parameters/has-since-changed-at
  responses:
    "200":
      description: OK
      headers:
        $ref: ../../components/responseHeader/responseHeader.yaml
      content:
        application/json:
          schema:
            type: object
            properties:
              results:
                type: string
                example: success
              data:
                type: array
                items:
                  $ref: ../../components/schemas/article-36-agreement-settings/get.yaml
    "400":
      $ref: ../../components/responses/common.yaml#/components/responses/commonResponse400
    "401":
      $ref: ../../components/responses/common.yaml#/components/responses/commonResponse401
    "403":
      $ref: ../../components/responses/common.yaml#/components/responses/commonResponse403
    "404":
      $ref: ../../components/responses/common.yaml#/components/responses/commonResponse404
    "405":
      $ref: ../../components/responses/common.yaml#/components/responses/commonResponse405
