get:
  tags:
    - 従業員 賞与振込設定
  summary: /v1/employees/bonus-transfer-settings
  description: "従業員に紐づく賞与振込設定を取得する。"
  operationId: Employees_bonus-transfer-settingsGetList
  security:
    - ApplicationJWT: []
  parameters:
    - $ref: ../../components/parameters/common.yaml#/components/parameters/page
    - $ref: ../../components/parameters/common.yaml#/components/parameters/employee-ids
    - $ref: ../../components/parameters/common.yaml#/components/parameters/has-since-changed-at
  responses:
    "200":
      description: OK
      headers:
        $ref: ../../components/responseHeader/responseHeader.yaml
      content:
        application/json:
          schema:
            type: object
            properties:
              results:
                type: string
                example: success
              data:
                type: array
                items:
                  $ref: ../../components/schemas/employees/bonus-transfer-settings/get.yaml
    "400":
      $ref: ../../components/responses/common.yaml#/components/responses/commonResponse400
    "401":
      $ref: ../../components/responses/common.yaml#/components/responses/commonResponse401
    "403":
      $ref: ../../components/responses/common.yaml#/components/responses/commonResponse403
    "404":
      $ref: ../../components/responses/common.yaml#/components/responses/commonResponse404
    "405":
      $ref: ../../components/responses/common.yaml#/components/responses/commonResponse405
post:
  tags:
    - 従業員 賞与振込設定
  summary: /v1/employees/bonus-transfer-settings
  description: "従業員に紐づく賞与振込設定を登録する。"
  operationId: Employees_bonus-transfer-settingsPost
  security:
    - ApplicationJWT: []
  parameters:
    - $ref: ../../components/parameters/common.yaml#/components/parameters/contentType
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: ../../components/schemas/employees/bonus-transfer-settings/post_body.yaml
  responses:
    "200":
      description: OK
      headers:
        $ref: ../../components/responseHeader/responseHeaderWithoutItemCount.yaml
      content:
        application/json:
          schema:
            type: object
            properties:
              results:
                type: string
                example: success
              data:
                $ref: ../../components/schemas/employees/bonus-transfer-settings/post.yaml
    "400":
      $ref: ../../components/responses/common.yaml#/components/responses/commonResponse400
    "401":
      $ref: ../../components/responses/common.yaml#/components/responses/commonResponse401
    "403":
      $ref: ../../components/responses/common.yaml#/components/responses/commonResponse403
    "404":
      $ref: ../../components/responses/common.yaml#/components/responses/commonResponse404
    "405":
      $ref: ../../components/responses/common.yaml#/components/responses/commonResponse405
patch:
  tags:
    - 従業員 賞与振込設定
  summary: /v1/employees/bonus-transfer-settings
  description: "従業員に紐づく賞与振込設定を更新する。"
  operationId: Employees_bonus-transfer-settingsPatch
  security:
    - ApplicationJWT: []
  parameters:
    - $ref: ../../components/parameters/common.yaml#/components/parameters/contentType
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: ../../components/schemas/employees/bonus-transfer-settings/patch_body.yaml
  responses:
    "200":
      description: OK
      headers:
        $ref: ../../components/responseHeader/responseHeaderWithoutItemCount.yaml
      content:
        application/json:
          schema:
            type: object
            properties:
              results:
                type: string
                example: success
              data:
                $ref: ../../components/schemas/employees/bonus-transfer-settings/post.yaml
    "400":
      $ref: ../../components/responses/common.yaml#/components/responses/commonResponse400
    "401":
      $ref: ../../components/responses/common.yaml#/components/responses/commonResponse401
    "403":
      $ref: ../../components/responses/common.yaml#/components/responses/commonResponse403
    "404":
      $ref: ../../components/responses/common.yaml#/components/responses/commonResponse404
    "405":
      $ref: ../../components/responses/common.yaml#/components/responses/commonResponse405
