get:
  tags:
    - 従業員 勤怠
  summary: /v1/employees/labor-hour-settings
  description: "従業員に紐づく勤怠情報を取得する。"
  operationId: employeeslaborhoursettingsGet
  security:
    - ApplicationJWT: []
  parameters:
    - $ref: ../../components/parameters/common.yaml#/components/parameters/page
    - $ref: ../../components/parameters/common.yaml#/components/parameters/employee-ids
    - $ref: ../../components/parameters/common.yaml#/components/parameters/has-since-changed-at
    - name: year
      in: query
      schema:
        type: string
        format: date
        pattern: "yyyy"
        example: "2023"
        description: "指定した年のデータを返却します。<br>年が指定されていない場合、全データを返却します。"
  responses:
    "200":
      description: OK
      headers:
        $ref: ../../components/responseHeader/responseHeader.yaml
      content:
        application/json:
          schema:
            type: object
            properties:
              results:
                type: string
                example: success
              data:
                type: array
                items:
                  $ref: ../../components/schemas/employees/labor-hour-settings/get.yaml
    '400':
      $ref: ../../components/responses/common.yaml#/components/responses/commonResponse400
    '401':
      $ref: ../../components/responses/common.yaml#/components/responses/commonResponse401
    '403':
      $ref: ../../components/responses/common.yaml#/components/responses/commonResponse403
    '404':
      $ref: ../../components/responses/common.yaml#/components/responses/commonResponse404
    '405':
      $ref: ../../components/responses/common.yaml#/components/responses/commonResponse405
post:
  tags:
    - 従業員 勤怠
  summary: /v1/employees/labor-hour-settings
  description: "従業員に紐づく勤怠情報を登録する。"
  operationId: employeeslaborhoursettingsPost
  security:
    - ApplicationJWT: []
  parameters:
    - $ref: ../../components/parameters/common.yaml#/components/parameters/contentType
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: ../../components/schemas/employees/labor-hour-settings/post_body.yaml
  responses:
    "200":
      description: OK
      headers:
        $ref: ../../components/responseHeader/responseHeaderWithoutItemCount.yaml
      content:
        application/json:
          schema:
            type: object
            properties:
              results:
                type: string
                example: success
              data:
                $ref: ../../components/schemas/employees/labor-hour-settings/post.yaml
    '400':
      $ref: ../../components/responses/common.yaml#/components/responses/commonResponse400
    '401':
      $ref: ../../components/responses/common.yaml#/components/responses/commonResponse401
    '403':
      $ref: ../../components/responses/common.yaml#/components/responses/commonResponse403
    '404':
      $ref: ../../components/responses/common.yaml#/components/responses/commonResponse404
    '405':
      $ref: ../../components/responses/common.yaml#/components/responses/commonResponse405
patch:
  tags:
    - 従業員 勤怠
  summary: /v1/employees/labor-hour-settings
  description: "従業員に紐づく勤怠情報を更新する。"
  operationId: employeeslaborhoursettingsPatch
  security:
    - ApplicationJWT: []
  parameters:
    - $ref: ../../components/parameters/common.yaml#/components/parameters/contentType
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: ../../components/schemas/employees/labor-hour-settings/patch_body.yaml
  responses:
    "200":
      description: OK
      headers:
        $ref: ../../components/responseHeader/responseHeaderWithoutItemCount.yaml
      content:
        application/json:
          schema:
            type: object
            properties:
              results:
                type: string
                example: success
              data:
                $ref: ../../components/schemas/employees/labor-hour-settings/post.yaml
    '400':
      $ref: ../../components/responses/common.yaml#/components/responses/commonResponse400
    '401':
      $ref: ../../components/responses/common.yaml#/components/responses/commonResponse401
    '403':
      $ref: ../../components/responses/common.yaml#/components/responses/commonResponse403
    '404':
      $ref: ../../components/responses/common.yaml#/components/responses/commonResponse404
    '405':
      $ref: ../../components/responses/common.yaml#/components/responses/commonResponse405
